#utils/swagger.yaml
openapi: 3.0.0
info:
  title: API de Blogging Interactiva
  version: 1.0.0
  description: Documentación de la API de Blogging Interactiva

servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /users:
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /posts:
    get:
      summary: Obtener todas las publicaciones
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /categories:
    get:
      summary: Obtener todas las categorías
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /comments:
    get:
      summary: Obtener todos los comentarios
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        roleId:
          type: integer
      required:
        - username
        - roleId

    Post:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content

    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - name

    Comment:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
      required:
        - content